backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Cover Image", name: "image", widget: "image" }

  - name: "settings"
    label: "Settings"
    files:
      - label: "Contact Info"
        name: contact_info
        file: site/settings/contact_info.json
        fields:
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - label: "Address"
            name: "address"
            widget: "object"
            fields:
              - { label: "Street", name: "street", widget: "string" }
              - { label: "City", name: "city", widget: "string" }
